#!/bin/bash
# chenwu@espressif.com
set -e

function ESP_DEL()
{
    if [ -e "$1" ]; then
        rm -rf $1
        ESP_LOGN "delete $1"
        sync
    fi
}

function ESP_IDF_CHECK()
{
    ESP_OBJ_CHECK "Makefile"

    if [ $IDF_PATH ]; then
        ESP_LOGI "IDF_PATH:$IDF_PATH"
    elif cat Makefile | grep "export IDF_PATH" > /dev/null; then
        ESP_LOGI "Implicit \$IDF_PATH found in Makefile"
    else
        ESP_LOGE "No \$IDF_PATH found, Please export \$IDF_PATH firstly!!!"
        exit
    fi
}

function ESP_OBJ_CHECK()
{
    if [ ! -e "$1" ]; then
        opath=`realpath .`
        ESP_LOGE "ERROR: No $1 in $opath, exit!!!"
        exit
    fi
}

function MEXIT()
{
    ESP_LOGE "$1, exit!!!"
    exit
}
